// Vorinstallierter Übungskatalog: die gängigsten Kraftsport-Übungen, damit man
// praktisch nie etwas von Hand anlegen muss. Die IDs sind bewusst aus dem Namen
// abgeleitet (statt zufällig), damit ein späteres Nachliefern neuer Übungen
// idempotent bleibt und nichts doppelt in der Bibliothek landet.

export const MUSCLE_GROUPS = [
  'Brust', 'Rücken', 'Schultern', 'Bizeps', 'Trizeps', 'Unterarme',
  'Bauch', 'Beine', 'Po', 'Waden', 'Ganzkörper', 'Cardio', 'Sonstiges',
];

const BY_GROUP = {
  Brust: [
    'Bankdrücken (Langhantel)',
    'Schrägbankdrücken (Langhantel)',
    'Negativbankdrücken (Langhantel)',
    'Bankdrücken (Kurzhantel)',
    'Schrägbankdrücken (Kurzhantel)',
    'Brustpresse (Maschine)',
    'Butterfly (Maschine)',
    'Fliegende (Kurzhantel)',
    'Schrägbank-Fliegende (Kurzhantel)',
    'Kabelzug-Fliegende (hoch)',
    'Kabelzug-Fliegende (tief)',
    'Liegestütze',
    'Dips (Brust)',
    'Überzüge (Pullover)',
  ],
  Rücken: [
    'Kreuzheben',
    'Sumo-Kreuzheben',
    'Rack Pulls',
    'Klimmzüge (Obergriff)',
    'Klimmzüge (Untergriff)',
    'Latzug (breit)',
    'Latzug (eng)',
    'Latzug (Untergriff)',
    'Langhantelrudern',
    'Langhantelrudern (Untergriff)',
    'Kurzhantelrudern (einarmig)',
    'T-Bar-Rudern',
    'Kabelrudern (sitzend)',
    'Rudern (Maschine)',
    'Überzüge am Kabel',
    'Rückenstrecker (Hyperextension)',
    'Good Mornings',
    'Nackenheben (Shrugs)',
    'Schrägbankrudern (Kurzhantel)',
    'Australian Pull-ups',
  ],
  Schultern: [
    'Schulterdrücken (Langhantel)',
    'Schulterdrücken (Kurzhantel)',
    'Schulterdrücken (Maschine)',
    'Militärpresse (stehend)',
    'Arnold-Press',
    'Seitheben (Kurzhantel)',
    'Seitheben (Kabel)',
    'Seitheben (Maschine)',
    'Frontheben (Kurzhantel)',
    'Frontheben (Langhantel)',
    'Vorgebeugtes Seitheben',
    'Reverse Butterfly (Maschine)',
    'Face Pulls',
    'Aufrechtes Rudern',
    'Landmine Press',
  ],
  Bizeps: [
    'Bizepscurls (Langhantel)',
    'Bizepscurls (Kurzhantel)',
    'Bizepscurls (SZ-Stange)',
    'Hammercurls',
    'Schrägbank-Curls',
    'Scott-Curls (Preacher)',
    'Konzentrationscurls',
    'Kabelcurls',
    'Spider Curls',
    'Bizepsmaschine',
  ],
  Trizeps: [
    'Trizepsdrücken am Kabel (Seil)',
    'Trizepsdrücken am Kabel (Stange)',
    'Stirndrücken (French Press)',
    'Überkopf-Trizepsdrücken (Kurzhantel)',
    'Überkopf-Trizepsdrücken (Kabel)',
    'Enges Bankdrücken',
    'Dips (Trizeps)',
    'Bankdips',
    'Trizeps-Kickbacks',
    'Trizepsmaschine',
  ],
  Unterarme: [
    'Handgelenk-Curls',
    'Reverse Handgelenk-Curls',
    'Reverse Curls',
    'Farmer’s Walk',
    'Hanging Hold (Griffkraft)',
  ],
  Bauch: [
    'Crunches',
    'Sit-ups',
    'Beinheben (hängend)',
    'Beinheben (liegend)',
    'Unterarmstütz (Plank)',
    'Seitlicher Unterarmstütz',
    'Russian Twists',
    'Bauchpresse (Maschine)',
    'Kabel-Crunches',
    'Bauchroller (Ab Wheel)',
    'Mountain Climbers',
    'Käfer (Dead Bug)',
    'Fahrrad-Crunches',
    'Toes to Bar',
    'Hollow Hold',
  ],
  Beine: [
    'Kniebeuge (Langhantel)',
    'Frontkniebeuge',
    'Goblet Squat',
    'Beinpresse',
    'Hackenschmidt-Kniebeuge',
    'Box Squat',
    'Ausfallschritte',
    'Walking Lunges',
    'Bulgarian Split Squat',
    'Step-Ups',
    'Beinstrecker',
    'Beinbeuger (liegend)',
    'Beinbeuger (sitzend)',
    'Rumänisches Kreuzheben',
    'Gestrecktes Kreuzheben',
    'Sissy Squat',
    'Adduktoren (Maschine)',
    'Nordic Curls',
  ],
  Po: [
    'Hip Thrust',
    'Glute Bridge',
    'Sumo-Kniebeuge',
    'Kickbacks (Kabel)',
    'Abduktoren (Maschine)',
    'Hip Thrust (Maschine)',
  ],
  Waden: [
    'Wadenheben (stehend)',
    'Wadenheben (sitzend)',
    'Wadenheben (Beinpresse)',
    'Eselswadenheben',
  ],
  Ganzkörper: [
    'Burpees',
    'Umsetzen (Power Clean)',
    'Umsetzen und Drücken',
    'Reißen (Snatch)',
    'Thrusters',
    'Kettlebell Swings',
    'Turkish Get-Up',
    'Medizinball-Slams',
    'Box Jumps',
  ],
  Cardio: [
    'Laufband',
    'Laufen (draußen)',
    'Crosstrainer',
    'Rudergerät',
    'Fahrradergometer',
    'Radfahren (draußen)',
    'Treppensteiger',
    'Seilspringen',
    'Schwimmen',
    'Assault Bike',
    'Battle Ropes',
    'Sprints',
  ],
};

function slug(name) {
  return name
    .toLowerCase()
    .replace(/ä/g, 'ae').replace(/ö/g, 'oe').replace(/ü/g, 'ue').replace(/ß/g, 'ss')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export const EXERCISE_CATALOG = Object.entries(BY_GROUP).flatMap(([muscleGroup, names]) =>
  names.map((name) => ({ id: `cat-${slug(name)}`, name, muscleGroup, notes: '' })),
);
