// Übungsbibliothek des Mobility-Bereichs.
//
// Die ursprünglichen 17 Übungen (Hüfte & Beine) stehen in mobility-data.js
// und bekommen hier ihre Einordnung: Körperregionen, Art, Varianten und den
// Hinweis fürs Anspannen-Loslassen. Dazu kommen Übungen für Oberkörper,
// Brustwirbelsäule, Schultern, Handgelenke, Nacken, Atmung und aktive
// Beweglichkeit – beschrieben im selben Posenformat (siehe mobility-figure.js).
//
// Regionen zählen die Wochenminuten: Entscheidend für mehr Beweglichkeit ist
// die Dehnzeit pro Region und Woche (ca. 5–10 Minuten, verteilt auf viele Tage).

import { MOBILITY_EXERCISES as BASE_EXERCISES, BREATH } from '../mobility-data.js';

const HOLD = { loop: BREATH.loop, breath: true };

export const REGIONS = [
  { id: 'neck', name: 'Nacken', short: 'Nacken' },
  { id: 'tspine', name: 'Brustwirbelsäule', short: 'BWS' },
  { id: 'shoulders', name: 'Schultern & Lat', short: 'Schultern' },
  { id: 'chest', name: 'Brust', short: 'Brust' },
  { id: 'wrists', name: 'Handgelenke', short: 'Hände' },
  { id: 'lowback', name: 'Unterer Rücken', short: 'Rücken' },
  { id: 'hipflex', name: 'Hüftbeuger & Oberschenkel vorn', short: 'Hüftbeuger' },
  { id: 'hiprot', name: 'Gesäß & Hüftrotation', short: 'Gesäß' },
  { id: 'adductors', name: 'Adduktoren', short: 'Adduktoren' },
  { id: 'hamstrings', name: 'Beinbeuger', short: 'Beinbeuger' },
  { id: 'calves', name: 'Waden & Sprunggelenke', short: 'Waden' },
];
export const REGION = Object.fromEntries(REGIONS.map((r) => [r.id, r]));

export const KINDS = {
  stretch: { label: 'Dehnen', hint: 'Ruhig halten, mit dem Ausatmen tiefer' },
  active: { label: 'Aktiv', hint: 'Kraft in der Endposition – macht Beweglichkeit nutzbar' },
  dynamic: { label: 'Dynamisch', hint: 'Fließend bewegen – ideal zum Aufwärmen' },
  breath: { label: 'Atmung', hint: 'Runterfahren und entspannen' },
};

// Einordnung der ursprünglichen Übungen
const META = {
  'hip-flexor': { regions: ['hipflex'], kind: 'stretch', up: 'couch-stretch', feel: 'Vorn an der Hüfte des hinteren Beins', pnf: 'Hinteres Knie sanft in den Boden drücken, als wolltest du es nach vorn ziehen.' },
  pigeon: { regions: ['hiprot'], kind: 'stretch', down: 'figure-four', feel: 'Tief im Gesäß des vorderen Beins', pnf: 'Vorderes Knie und Schienbein sanft in den Boden drücken.' },
  'ninety-switch': { regions: ['hiprot'], kind: 'dynamic', up: 'ninety-liftoff', feel: 'Rund um beide Hüftgelenke' },
  'ninety-hold': { regions: ['hiprot'], kind: 'stretch', feel: 'Gesäß und Außenseite der vorderen Hüfte', pnf: 'Vorderes Schienbein sanft in den Boden drücken.' },
  frog: { regions: ['adductors'], kind: 'stretch', feel: 'Innenseite beider Oberschenkel', pnf: 'Knie sanft in den Boden drücken, als wolltest du sie zusammenziehen.' },
  'hamstring-supine': { regions: ['hamstrings'], kind: 'stretch', up: 'half-split', feel: 'Rückseite des Oberschenkels, bis in die Kniekehle', pnf: 'Ferse gegen das Handtuch sanft Richtung Boden drücken.' },
  'deep-squat': { regions: ['calves', 'adductors'], kind: 'stretch', up: 'squat-shift', feel: 'Waden, Sprunggelenke und Leiste' },
  'calf-wall': { regions: ['calves'], kind: 'stretch', feel: 'Wade des hinteren Beins', pnf: 'Fußballen hinten sanft in den Boden drücken.' },
  butterfly: { regions: ['adductors'], kind: 'stretch', up: 'frog', feel: 'Leiste und Innenseite der Oberschenkel', pnf: 'Knie sanft gegen die Hände nach oben drücken.' },
  straddle: { regions: ['adductors', 'hamstrings'], kind: 'stretch', up: 'pancake-reach', feel: 'Innenseite und Rückseite der Beine', pnf: 'Fersen sanft in den Boden drücken.' },
  'supine-twist': { regions: ['lowback', 'hiprot'], kind: 'stretch', feel: 'Seitlich im Gesäß und unteren Rücken' },
  'worlds-greatest': { regions: ['hipflex', 'tspine'], kind: 'dynamic', feel: 'Hüfte, Leiste und oberer Rücken' },
  cossack: { regions: ['adductors'], kind: 'active', feel: 'Innenseite des gestreckten Beins' },
  'leg-swing': { regions: ['hamstrings', 'hipflex'], kind: 'dynamic', feel: 'Vorder- und Rückseite der Hüfte' },
  'knee-to-wall': { regions: ['calves'], kind: 'dynamic', feel: 'Wade und vorderes Sprunggelenk' },
  'forward-fold': { regions: ['hamstrings', 'lowback'], kind: 'stretch', up: 'seated-pike', feel: 'Rückseite der Beine' },
  'hip-circles': { regions: ['hiprot'], kind: 'dynamic', feel: 'Rund um das Hüftgelenk' },
};

// Grundhaltungen
const STAND = {
  pelvis: [0, 0.98, 0],
  footL: [0.11, 0.08, 0], footR: [-0.11, 0.08, 0],
  kneeL: [0.11, 0.5, 0.3], kneeR: [-0.11, 0.5, 0.3],
  toeL: [0.13, 0.03, 0.17], toeR: [-0.13, 0.03, 0.17],
  handL: [0.24, 0.84, 0.02], handR: [-0.24, 0.84, 0.02],
  elbowL: [0.32, 1.1, -0.2], elbowR: [-0.32, 1.1, -0.2],
};
const QUAD = {
  pelvis: [0, 0.55, -0.1], pUp: [0, 0.08, 1], pFwd: [0, -1, 0.08], cUp: [0, 0.14, 1], cFwd: [0, -1, 0.14],
  footL: [0.1, 0.07, -0.55], kneeL: [0.1, -0.1, -0.1], toeL: [0.1, 0.02, -0.7],
  footR: [-0.1, 0.07, -0.55], kneeR: [-0.1, -0.1, -0.1], toeR: [-0.1, 0.02, -0.7],
  handL: [0.2, 0.06, 0.42], handR: [-0.2, 0.06, 0.42],
  elbowL: [0.3, 0.3, 0.1], elbowR: [-0.3, 0.3, 0.1],
};
// Rückenlage: Kopf bei -z
const SUPINE = { pelvis: [0, 0.12, 0], pUp: [0, 0, -1], pFwd: [0, 1, 0], cUp: [0, 0, -1], cFwd: [0, 1, 0] };
// Wand auf der rechten Seite zum Festhalten
const WALL_RIGHT = { handR: [-0.5, 1.18, 0.06], elbowR: [-0.5, 1.0, -0.3] };

const EXTRA = [
  // ---------- Wirbelsäule & Oberkörper ----------
  {
    id: 'cat-cow',
    name: 'Katze-Kuh',
    regions: ['tspine', 'lowback'],
    kind: 'dynamic',
    type: 'flow',
    sides: false,
    seconds: 40,
    tempo: 'Mit dem Atem, ca. 4 Sekunden pro Richtung',
    why: 'Bewegt die ganze Wirbelsäule Wirbel für Wirbel – der sanfteste Start in den Tag und ins Training.',
    feel: 'Ganzer Rücken, zwischen den Schulterblättern',
    cues: [
      'Vierfüßlerstand: Hände unter den Schultern, Knie unter der Hüfte.',
      'Einatmen: Bauch sinken lassen, Brust und Blick nach vorn-oben.',
      'Ausatmen: Rücken rund machen, Kinn zur Brust, Bauchnabel nach innen.',
    ],
    mistakes: ['Nur den Nacken bewegen – die Welle soll vom Becken bis zum Kopf laufen.'],
    easier: 'Kleinere Bewegung, nur im mittleren Rücken.',
    harder: 'In jeder Endposition zwei Atemzüge bleiben.',
    cam: { az: 90, el: 12 },
    highlight: ['chest', 'abdomen'],
    loop: 8,
    base: { ...QUAD },
    frames: [
      { t: 0, p: { pUp: [0, -0.3, 1], cUp: [0, 0.5, 1], hUp: [0, 1, 0.9] } },
      { t: 1.2, p: { pUp: [0, -0.3, 1], cUp: [0, 0.5, 1], hUp: [0, 1, 0.9] } },
      { t: 4, p: { pUp: [0, 0.5, 1], cUp: [0, -0.35, 1], hUp: [0, -1, 0.5] } },
      { t: 5.2, p: { pUp: [0, 0.5, 1], cUp: [0, -0.35, 1], hUp: [0, -1, 0.5] } },
    ],
  },
  {
    id: 'thread-needle',
    name: 'Nadel einfädeln',
    regions: ['tspine', 'shoulders'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 30,
    why: 'Dreht die Brustwirbelsäule und dehnt die Schulter hinten – Gegenmittel zum runden Schreibtisch- und Deckungsrücken.',
    feel: 'Hinten an der Schulter und zwischen den Schulterblättern',
    cues: [
      'Vierfüßlerstand, einen Arm unter dem Körper zur anderen Seite schieben.',
      'Schulter und Schläfe sinken Richtung Boden.',
      'Die Hüfte bleibt über den Knien, der Blick folgt der Hand.',
    ],
    mistakes: ['Mit der Hüfte zur Seite ausweichen.'],
    easier: 'Nur so weit schieben, bis die Schulter zu sinken beginnt.',
    harder: 'Die andere Hand über den Kopf nach vorn strecken.',
    pnf: 'Handrücken der unteren Hand sanft in den Boden drücken.',
    cam: { az: 55, el: 30 },
    highlight: ['shoulderL', 'upperArmL'],
    ...HOLD,
    base: {
      ...QUAD,
      pelvis: [0, 0.55, -0.14],
      handR: [-0.16, 0.06, 0.44], elbowR: [-0.5, 0.45, 0.35],
      elbowL: [0.0, 0.2, 0.3],
    },
    frames: [
      { t: 0, p: { cUp: [0, -0.02, 1], cFwd: [-0.6, -0.8, 0], hUp: [-0.25, 0, 1], look: [-0.7, 0.2, 0], handL: [-0.3, 0.08, 0.34] } },
      { t: 3, p: { cUp: [0, -0.12, 1], cFwd: [-0.8, -0.6, 0], hUp: [-0.35, -0.1, 1], look: [-0.8, 0.4, 0], handL: [-0.46, 0.08, 0.32] } },
    ],
  },
  {
    id: 'open-book',
    name: 'Offenes Buch',
    regions: ['tspine', 'chest'],
    kind: 'dynamic',
    type: 'flow',
    sides: true,
    seconds: 30,
    tempo: 'Langsam, ca. 4 pro Seite, offen kurz bleiben',
    why: 'Die Brustwirbelsäule dreht sich im Alltag kaum noch. Hier öffnet sie sich, ohne dass der untere Rücken mitdreht.',
    feel: 'Brust vorn und zwischen den Schulterblättern',
    cues: [
      'Auf die Seite legen, Knie 90° angewinkelt, Arme gestreckt übereinander.',
      'Den oberen Arm in einem großen Bogen zur anderen Seite öffnen.',
      'Der Blick folgt der Hand, die Knie bleiben aufeinander liegen.',
    ],
    mistakes: ['Das obere Knie rutscht nach hinten – dann dreht der untere Rücken statt der Brust.'],
    easier: 'Nur bis zur Senkrechten öffnen.',
    harder: 'Offen zwei ruhige Atemzüge halten.',
    cam: { az: -60, el: 42 },
    highlight: ['chest'],
    smooth: true,
    loop: 8,
    base: {
      pelvis: [0, 0.2, 0], pUp: [0, 0, -1], pFwd: [-1, 0, 0],
      kneeL: [-0.42, 0.24, 0.02], footL: [-0.42, 0.22, 0.42], toeL: [-0.44, 0.2, 0.58],
      kneeR: [-0.42, 0.08, 0.02], footR: [-0.42, 0.07, 0.42], toeR: [-0.44, 0.05, 0.58],
      handR: [-0.56, 0.06, -0.48], elbowR: [-0.3, 0.05, -0.5],
      cUp: [0, 0, -1],
    },
    frames: [
      { t: 0, p: { cFwd: [-1, 0.05, 0], handL: [-0.56, 0.16, -0.48], elbowL: [-0.3, 0.3, -0.5] } },
      { t: 1, p: { cFwd: [-1, 0.05, 0], handL: [-0.56, 0.16, -0.48], elbowL: [-0.3, 0.3, -0.5] } },
      { t: 2.8, p: { cFwd: [-0.7, 0.7, 0], handL: [-0.05, 0.85, -0.5], elbowL: [-0.1, 0.6, -0.5] } },
      { t: 4.4, p: { cFwd: [0.1, 1, 0], handL: [0.52, 0.12, -0.5], elbowL: [0.3, 0.3, -0.5] } },
      { t: 5.6, p: { cFwd: [0.1, 1, 0], handL: [0.52, 0.12, -0.5], elbowL: [0.3, 0.3, -0.5] } },
      { t: 7, p: { cFwd: [-0.7, 0.7, 0], handL: [-0.05, 0.85, -0.5], elbowL: [-0.1, 0.6, -0.5] } },
    ],
  },
  {
    id: 'sphinx',
    name: 'Sphinx',
    regions: ['lowback', 'hipflex'],
    kind: 'stretch',
    type: 'hold',
    sides: false,
    seconds: 45,
    why: 'Sanfte Streckung für einen Rücken, der den ganzen Tag gebeugt ist – öffnet dazu Bauch und Hüfte.',
    feel: 'Unterer Rücken und Bauch, angenehmes Aufrichten',
    cues: [
      'Auf den Bauch legen, Ellbogen unter die Schultern.',
      'Brust nach vorn-oben schieben, Schultern weg von den Ohren.',
      'Gesäß locker lassen, ruhig in den Bauch atmen.',
    ],
    mistakes: ['Schultern hochziehen oder den Kopf in den Nacken legen.'],
    easier: 'Ellbogen etwas weiter nach vorn.',
    harder: 'Auf die gestreckten Arme hochdrücken (Kobra) – nur wenn es angenehm bleibt.',
    cam: { az: 70, el: 14 },
    highlight: ['abdomen'],
    ...HOLD,
    base: {
      pelvis: [0, 0.12, 0], pUp: [0, 0, 1], pFwd: [0, -1, 0],
      footL: [0.11, 0.06, -0.85], toeL: [0.11, 0.03, -1.02], kneeL: [0.11, 0.2, -0.4],
      footR: [-0.11, 0.06, -0.85], toeR: [-0.11, 0.03, -1.02], kneeR: [-0.11, 0.2, -0.4],
      cFwd: [0, -1, 0.6],
      handL: [0.14, 0.05, 0.72], handR: [-0.14, 0.05, 0.72],
      elbowL: [0.22, -0.3, 0.42], elbowR: [-0.22, -0.3, 0.42],
      hUp: [0, 1, 0.55], look: [0, 0, 1],
    },
    frames: [
      { t: 0, p: { cUp: [0, 0.75, 1] } },
      { t: 3, p: { cUp: [0, 0.95, 1] } },
    ],
  },
  {
    id: 'child-pose',
    name: 'Kindhaltung',
    regions: ['lowback', 'shoulders'],
    kind: 'stretch',
    type: 'hold',
    sides: false,
    seconds: 45,
    why: 'Die klassische Ruheposition: entlastet den Rücken, dehnt Lat und Hüfte sanft und beruhigt den Atem.',
    feel: 'Unterer Rücken, Seiten des Oberkörpers',
    cues: [
      'Knie hüftbreit, Gesäß Richtung Fersen sinken lassen.',
      'Arme lang nach vorn, Stirn ablegen.',
      'Tief in den unteren Rücken und die Flanken atmen.',
    ],
    mistakes: ['Das Gesäß schwebt hoch über den Fersen – Knie weiter öffnen.'],
    easier: 'Ein Kissen zwischen Gesäß und Fersen.',
    harder: 'Hände weiter nach vorn laufen lassen.',
    cam: { az: 90, el: 16 },
    highlight: ['abdomen'],
    ...HOLD,
    base: {
      pUp: [0, 0.35, 1], cFwd: [0, -1, -0.2],
      footL: [0.12, 0.07, -0.34], toeL: [0.12, 0.02, -0.5], kneeL: [0.18, -0.2, 0.3],
      footR: [-0.12, 0.07, -0.34], toeR: [-0.12, 0.02, -0.5], kneeR: [-0.18, -0.2, 0.3],
      elbowL: [0.3, 0.3, 0.5], elbowR: [-0.3, 0.3, 0.5],
      hUp: [0, -0.6, 1],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.33, -0.2], cUp: [0, -0.12, 1], handL: [0.2, 0.05, 0.78], handR: [-0.2, 0.05, 0.78] } },
      { t: 3, p: { pelvis: [0, 0.29, -0.25], cUp: [0, -0.25, 1], handL: [0.2, 0.05, 0.8], handR: [-0.2, 0.05, 0.8] } },
    ],
  },
  {
    id: 'child-side',
    name: 'Seitliche Kindhaltung',
    regions: ['shoulders', 'lowback'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 30,
    why: 'Dehnt den breiten Rückenmuskel (Lat) – der hält die Arme beim Überkopfdrücken und beim Schlagen zurück.',
    feel: 'Seitlich am Oberkörper, von der Achsel bis zur Hüfte',
    cues: [
      'Aus der Kindhaltung beide Hände zur Seite wandern lassen.',
      'Gesäß bleibt auf den Fersen, die Gegenseite wird lang.',
      'In die gedehnte Flanke atmen.',
    ],
    mistakes: ['Das Gesäß kippt mit zur Seite.'],
    easier: 'Hände nur ein kleines Stück zur Seite.',
    harder: 'Die obere Hand über die untere legen.',
    pnf: 'Handfläche des gedehnten Arms sanft in den Boden drücken.',
    cam: { az: 20, el: 30 },
    highlight: ['upperArmL', 'chest'],
    ...HOLD,
    base: {
      pUp: [-0.1, 0.35, 1], cFwd: [0, -1, -0.2],
      footL: [0.12, 0.07, -0.34], toeL: [0.12, 0.02, -0.5], kneeL: [0.18, -0.2, 0.3],
      footR: [-0.12, 0.07, -0.34], toeR: [-0.12, 0.02, -0.5], kneeR: [-0.18, -0.2, 0.3],
      elbowL: [0.1, 0.35, 0.5], elbowR: [-0.5, 0.3, 0.3],
      hUp: [-0.3, -0.6, 1],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.33, -0.2], cUp: [-0.35, -0.12, 1], handL: [-0.3, 0.05, 0.74], handR: [-0.5, 0.05, 0.58] } },
      { t: 3, p: { pelvis: [0.02, 0.3, -0.24], cUp: [-0.55, -0.2, 1], handL: [-0.4, 0.05, 0.7], handR: [-0.58, 0.05, 0.5] } },
    ],
  },
  {
    id: 'puppy',
    name: 'Welpe (Brustöffner)',
    regions: ['shoulders', 'tspine', 'chest'],
    kind: 'stretch',
    type: 'hold',
    sides: false,
    seconds: 45,
    why: 'Öffnet Schultern und oberen Rücken in Überkopf-Position – für freie Arme beim Drücken, Ziehen und in der Deckung.',
    feel: 'Achseln, Schultern und Brust',
    cues: [
      'Knie unter der Hüfte, Hände weit nach vorn laufen lassen.',
      'Brust Richtung Boden sinken lassen, Gesäß bleibt über den Knien.',
      'Arme lang, die Achseln drücken sanft zum Boden.',
    ],
    mistakes: ['Ins Hohlkreuz fallen – Bauch leicht anspannen.'],
    easier: 'Unterarme ablegen statt der Hände.',
    harder: 'Hände auf einen Block oder ein Buch legen.',
    pnf: 'Hände sanft in den Boden drücken, als wolltest du sie zu dir ziehen.',
    cam: { az: 80, el: 12 },
    highlight: ['shoulderL', 'shoulderR', 'chest'],
    ...HOLD,
    base: {
      pelvis: [0, 0.54, -0.12], pUp: [0, -0.35, 1], pFwd: [0, -1, -0.35],
      footL: [0.1, 0.07, -0.56], kneeL: [0.1, -0.2, -0.12], toeL: [0.1, 0.02, -0.72],
      footR: [-0.1, 0.07, -0.56], kneeR: [-0.1, -0.2, -0.12], toeR: [-0.1, 0.02, -0.72],
      elbowL: [0.25, 0.4, 0.5], elbowR: [-0.25, 0.4, 0.5],
      cFwd: [0, -1, -0.6], hUp: [0, -0.35, 1],
    },
    frames: [
      { t: 0, p: { cUp: [0, -0.9, 1], handL: [0.2, 0.05, 0.78], handR: [-0.2, 0.05, 0.78] } },
      { t: 3, p: { cUp: [0, -1.3, 1], handL: [0.2, 0.05, 0.78], handR: [-0.2, 0.05, 0.78] } },
    ],
  },
  {
    id: 'doorway-pec',
    name: 'Brustdehnung im Türrahmen',
    regions: ['chest', 'shoulders'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 30,
    why: 'Bankdrücken, Handy, Deckung – alles zieht die Schultern nach vorn. Diese Dehnung holt sie zurück.',
    feel: 'Vorn an der Brust und Schulter',
    cues: [
      'Unterarm an den Türrahmen, Ellbogen auf Schulterhöhe.',
      'Einen kleinen Schritt nach vorn, Brust sanft durch die Tür schieben.',
      'Den Oberkörper leicht von der Wand wegdrehen.',
    ],
    mistakes: ['Die Schulter rutscht nach vorn oben – Schulterblatt nach hinten unten ziehen.'],
    easier: 'Ellbogen etwas tiefer, kleinerer Schritt.',
    harder: 'Ellbogen höher ansetzen – dehnt den unteren Teil der Brust.',
    pnf: 'Unterarm sanft gegen den Türrahmen drücken.',
    cam: { az: -145, el: 14 },
    highlight: ['chest', 'shoulderL'],
    props: [{ type: 'wall', x: 0.52 }],
    mat: { hidden: true },
    ...HOLD,
    base: {
      ...STAND,
      footL: [0.12, 0.08, 0.12], toeL: [0.14, 0.03, 0.29], kneeL: [0.12, 0.5, 0.45],
      footR: [-0.12, 0.08, -0.2], toeR: [-0.14, 0.03, -0.03],
      elbowL: [0.48, 1.4, -0.12], handL: [0.48, 1.66, -0.1],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.98, 0], cFwd: [-0.15, 0, 1] } },
      { t: 3, p: { pelvis: [0, 0.97, 0.05], cFwd: [-0.35, 0, 1] } },
    ],
  },
  {
    id: 'wall-slide',
    name: 'Wall Slides',
    regions: ['shoulders', 'tspine'],
    kind: 'active',
    type: 'flow',
    sides: false,
    seconds: 40,
    tempo: 'Langsam, oben kurz halten',
    why: 'Trainiert die Muskeln, die die Arme über den Kopf bringen und die Schulterblätter führen – Beweglichkeit, die hält.',
    feel: 'Zwischen den Schulterblättern und hinten an den Schultern',
    cues: [
      'Rücken, Hinterkopf und Unterarme an die Wand, Arme wie ein W.',
      'Arme langsam nach oben schieben, ohne dass etwas abhebt.',
      'Unten die Schulterblätter bewusst nach hinten unten ziehen.',
    ],
    mistakes: ['Hohlkreuz – Bauch anspannen, der untere Rücken bleibt an der Wand.'],
    easier: 'Einen Schritt weg von der Wand, nur die Unterarme berühren sie.',
    harder: 'Oben kurz die Hände von der Wand lösen.',
    cam: { az: 25, el: 10 },
    highlight: ['shoulderL', 'shoulderR', 'upperArmL', 'upperArmR'],
    props: [{ type: 'wall', z: -0.22 }],
    mat: { hidden: true },
    smooth: true,
    loop: 5,
    base: {
      ...STAND,
      pelvis: [0, 0.94, -0.06],
      footL: [0.13, 0.08, 0.14], footR: [-0.13, 0.08, 0.14],
      toeL: [0.15, 0.03, 0.31], toeR: [-0.15, 0.03, 0.31],
      kneeL: [0.13, 0.5, 0.5], kneeR: [-0.13, 0.5, 0.5],
      cUp: [0, 1, -0.04],
    },
    frames: [
      { t: 0, p: { handL: [0.34, 1.55, -0.13], elbowL: [0.44, 1.3, -0.14], handR: [-0.34, 1.55, -0.13], elbowR: [-0.44, 1.3, -0.14] } },
      { t: 0.8, p: { handL: [0.34, 1.55, -0.13], elbowL: [0.44, 1.3, -0.14], handR: [-0.34, 1.55, -0.13], elbowR: [-0.44, 1.3, -0.14] } },
      { t: 2.5, p: { handL: [0.3, 1.98, -0.13], elbowL: [0.4, 1.75, -0.14], handR: [-0.3, 1.98, -0.13], elbowR: [-0.4, 1.75, -0.14] } },
      { t: 3.3, p: { handL: [0.3, 1.98, -0.13], elbowL: [0.4, 1.75, -0.14], handR: [-0.3, 1.98, -0.13], elbowR: [-0.4, 1.75, -0.14] } },
    ],
  },
  {
    id: 'towel-dislocate',
    name: 'Schulterkreisen mit Handtuch',
    regions: ['shoulders', 'chest'],
    kind: 'dynamic',
    type: 'flow',
    sides: false,
    seconds: 40,
    tempo: 'Langsam, ca. 6 Durchgänge',
    why: 'Führt die Schultern durch ihren ganzen Bewegungsweg – ideal vor dem Oberkörper-Training und dem Boxen.',
    feel: 'Vorn an den Schultern und in der Brust',
    cues: [
      'Handtuch oder Gürtel sehr breit greifen, Arme gestreckt.',
      'In einem großen Bogen über den Kopf nach hinten führen.',
      'Und auf demselben Weg zurück – die Arme bleiben gestreckt.',
    ],
    mistakes: ['Zu eng greifen und mit dem Rücken ausweichen.'],
    easier: 'Noch breiter greifen und nur bis über den Kopf gehen.',
    harder: 'Mit jedem Durchgang etwas enger greifen.',
    cam: { az: 60, el: 8 },
    highlight: ['shoulderL', 'shoulderR'],
    props: [{ type: 'strap', from: 'handL', to: 'handR' }],
    mat: { hidden: true },
    smooth: true,
    loop: 7.2,
    base: { ...STAND, elbowL: [0.7, 1.4, 0.0], elbowR: [-0.7, 1.4, 0.0] },
    frames: [
      { t: 0, p: { handL: [0.52, 1.0, 0.32], handR: [-0.52, 1.0, 0.32] } },
      { t: 1.2, p: { handL: [0.52, 1.6, 0.42], handR: [-0.52, 1.6, 0.42] } },
      { t: 2.4, p: { handL: [0.52, 1.95, 0.02], handR: [-0.52, 1.95, 0.02] } },
      { t: 3.6, p: { handL: [0.52, 1.35, -0.42], handR: [-0.52, 1.35, -0.42] } },
      { t: 4.8, p: { handL: [0.52, 1.95, 0.02], handR: [-0.52, 1.95, 0.02] } },
      { t: 6.0, p: { handL: [0.52, 1.6, 0.42], handR: [-0.52, 1.6, 0.42] } },
    ],
  },
  {
    id: 'wrist-rock',
    name: 'Handgelenke im Vierfüßlerstand',
    regions: ['wrists'],
    kind: 'stretch',
    type: 'flow',
    sides: false,
    seconds: 40,
    tempo: 'Langsam vor und zurück wippen',
    why: 'Schläge, Liegestütze und Bankdrücken belasten die Handgelenke – so bleiben sie beweglich und belastbar.',
    feel: 'Unterarme innen und Handgelenke',
    cues: [
      'Vierfüßlerstand, Finger zeigen zu den Knien, Handflächen flach.',
      'Gesäß langsam Richtung Fersen schieben, bis die Unterarme ziehen.',
      'Dann Handrücken aufsetzen und dasselbe sanft wiederholen.',
    ],
    mistakes: ['Die Handballen heben ab.'],
    easier: 'Weniger weit zurück wippen.',
    harder: 'Hinten zwei Atemzüge halten.',
    cam: { az: 60, el: 22 },
    highlight: ['foreArmL', 'foreArmR'],
    loop: 4.4,
    base: { ...QUAD, handL: [0.18, 0.06, 0.34], handR: [-0.18, 0.06, 0.34], elbowL: [0.2, 0.3, 0.6], elbowR: [-0.2, 0.3, 0.6] },
    frames: [
      { t: 0, p: { pelvis: [0, 0.55, -0.06] } },
      { t: 0.6, p: { pelvis: [0, 0.55, -0.06] } },
      { t: 2.2, p: { pelvis: [0, 0.47, -0.24], pUp: [0, 0.3, 1] } },
      { t: 3.2, p: { pelvis: [0, 0.47, -0.24], pUp: [0, 0.3, 1] } },
    ],
  },
  {
    id: 'neck-side',
    name: 'Nacken seitlich',
    regions: ['neck'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 25,
    why: 'Löst den oberen Trapezmuskel – der verspannt beim Sitzen, Schreiben und in der hochgezogenen Deckung.',
    feel: 'Seitlich am Hals bis zur Schulter',
    cues: [
      'Aufrecht stehen, Kopf zur Seite neigen – Ohr Richtung Schulter.',
      'Die Hand liegt nur locker auf dem Kopf, sie zieht nicht.',
      'Die andere Schulter aktiv nach unten schieben.',
    ],
    mistakes: ['Am Kopf ziehen oder die Schulter hochziehen.'],
    easier: 'Ohne Hand, nur den Kopf neigen.',
    harder: 'Blick leicht zur Achsel drehen – dehnt weiter hinten.',
    pnf: 'Kopf sanft gegen die Hand drücken, ohne dass er sich bewegt.',
    cam: { az: 20, el: 6 },
    highlight: ['neckSeg'],
    mat: { hidden: true },
    ...HOLD,
    base: { ...STAND, elbowR: [-0.4, 1.72, 0.05], handL: [0.26, 0.8, 0.0] },
    frames: [
      { t: 0, p: { hUp: [-0.6, 1, 0.04], handR: [0.0, 1.74, 0.03] } },
      { t: 3, p: { hUp: [-0.85, 1, 0.04], handR: [-0.04, 1.71, 0.03] } },
    ],
  },
  {
    id: 'seated-twist',
    name: 'Drehsitz',
    regions: ['tspine', 'hiprot'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 35,
    why: 'Dreht die Wirbelsäule unter Aufrichtung und dehnt dabei das Gesäß – Rotation ist die Grundlage jedes Schlags.',
    feel: 'Außen an der Hüfte und entlang des Rückens',
    cues: [
      'Ein Bein lang, den anderen Fuß außen über das Knie stellen.',
      'Mit dem Einatmen groß werden, mit dem Ausatmen weiter drehen.',
      'Der Ellbogen drückt sanft gegen das aufgestellte Knie.',
    ],
    mistakes: ['Rundrücken – erst aufrichten, dann drehen.'],
    easier: 'Das Knie nur mit der Hand umarmen.',
    harder: 'Das untere Bein ebenfalls anwinkeln.',
    pnf: 'Knie sanft gegen den Ellbogen drücken.',
    cam: { az: 30, el: 24 },
    highlight: ['chest', 'thighL'],
    ...HOLD,
    base: {
      pelvis: [0, 0.14, 0], pUp: [0, 1, -0.05],
      footR: [-0.09, 0.07, 0.86], kneeR: [-0.09, 0.5, 0.45], toeR: [-0.09, 0.22, 0.9],
      footL: [-0.2, 0.07, 0.34], kneeL: [0.2, 0.6, 0.3], toeL: [-0.22, 0.02, 0.5],
      handL: [0.18, 0.06, -0.32], elbowL: [0.35, 0.3, -0.2],
      handR: [0.12, 0.48, 0.3], elbowR: [0.02, 0.5, 0.3],
    },
    frames: [
      { t: 0, p: { cFwd: [0.45, 0, 0.9], look: [0.75, 0, 0.6] } },
      { t: 3, p: { cFwd: [0.75, 0, 0.65], look: [0.95, 0, 0.25] } },
    ],
  },
  {
    id: 'side-bend',
    name: 'Seitneigung im Stand',
    regions: ['shoulders', 'lowback'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 25,
    why: 'Macht die Flanke lang – gut zwischendurch am Schreibtisch und morgens zum Wachwerden.',
    feel: 'Seitlich von der Hüfte bis in die Achsel',
    cues: [
      'Hüftbreit stehen, einen Arm über den Kopf strecken.',
      'Zur Gegenseite neigen, als würdest du nach oben-drüben greifen.',
      'Becken bleibt über den Füßen.',
    ],
    mistakes: ['Nach vorn kippen statt zur Seite.'],
    easier: 'Die andere Hand auf die Hüfte stützen.',
    harder: 'Beide Hände über dem Kopf greifen.',
    cam: { az: 0, el: 6 },
    highlight: ['chest', 'upperArmL'],
    mat: { hidden: true },
    ...HOLD,
    base: {
      ...STAND,
      footL: [0.15, 0.08, 0], footR: [-0.15, 0.08, 0], toeL: [0.17, 0.03, 0.17], toeR: [-0.17, 0.03, 0.17],
      kneeL: [0.15, 0.5, 0.3], kneeR: [-0.15, 0.5, 0.3],
      elbowL: [0.35, 1.9, 0.0], handR: [-0.28, 0.98, 0.08], elbowR: [-0.45, 1.1, -0.1],
    },
    frames: [
      { t: 0, p: { pUp: [-0.05, 1, 0], cUp: [-0.25, 1, 0], handL: [-0.18, 1.98, 0.02] } },
      { t: 3, p: { pUp: [-0.1, 1, 0], cUp: [-0.45, 1, 0], handL: [-0.32, 1.9, 0.02] } },
    ],
  },
  // ---------- Atmung & Entspannung ----------
  {
    id: 'breath-9090',
    name: '90/90-Atmung',
    regions: [],
    kind: 'breath',
    type: 'hold',
    sides: false,
    seconds: 60,
    why: 'Füße an der Wand, tief in den Bauch und die Flanken atmen: beruhigt das Nervensystem und entspannt den unteren Rücken.',
    feel: 'Bauch und untere Rippen weiten sich',
    cues: [
      'Rücken liegt am Boden, Füße an der Wand, Knie und Hüfte 90°.',
      '4 Sekunden durch die Nase einatmen – Bauch und Flanken weiten sich.',
      '6 Sekunden langsam ausatmen, als würdest du eine Kerze auspusten.',
    ],
    mistakes: ['In die Brust atmen und die Schultern heben.'],
    easier: 'Unterschenkel auf einen Stuhl legen.',
    harder: 'Beim Ausatmen die Fersen sanft in die Wand drücken.',
    cam: { az: 104, el: 20 },
    highlight: ['abdomen'],
    props: [{ type: 'wall', z: 0.5 }],
    loop: 10,
    breath: false,
    base: {
      ...SUPINE,
      kneeL: [0.1, 0.56, -0.02], footL: [0.1, 0.52, 0.42], toeL: [0.1, 0.68, 0.46],
      kneeR: [-0.1, 0.56, -0.02], footR: [-0.1, 0.52, 0.42], toeR: [-0.1, 0.68, 0.46],
      handL: [0.1, 0.22, -0.2], handR: [-0.1, 0.22, -0.3],
      elbowL: [0.35, 0.05, -0.25], elbowR: [-0.35, 0.05, -0.32],
    },
    frames: [
      { t: 0, p: { cUp: [0, 0.0, -1] } },
      { t: 4, p: { cUp: [0, 0.06, -1] } },
    ],
  },
  {
    id: 'knees-chest',
    name: 'Knie zur Brust',
    regions: ['lowback', 'hiprot'],
    kind: 'stretch',
    type: 'hold',
    sides: false,
    seconds: 40,
    why: 'Rundet und entlastet den unteren Rücken – nach Kreuzheben, Kniebeugen oder einem langen Tag.',
    feel: 'Unterer Rücken und Gesäß',
    cues: [
      'Auf den Rücken legen, beide Knie zur Brust ziehen.',
      'Hände unter den Knien, Schultern locker am Boden.',
      'Leicht hin und her wiegen, wenn es gut tut.',
    ],
    mistakes: ['Kopf und Schultern vom Boden heben.'],
    easier: 'Ein Knie nach dem anderen.',
    harder: 'Mit dem Ausatmen die Knie etwas näher ziehen.',
    cam: { az: 40, el: 40 },
    highlight: ['abdomen', 'pelvis'],
    ...HOLD,
    base: {
      ...SUPINE,
      elbowL: [0.4, 0.3, -0.3], elbowR: [-0.4, 0.3, -0.3],
    },
    frames: [
      {
        t: 0,
        p: {
          kneeL: [0.12, 0.47, -0.18], footL: [0.12, 0.3, 0.14], toeL: [0.12, 0.38, 0.26],
          kneeR: [-0.12, 0.47, -0.18], footR: [-0.12, 0.3, 0.14], toeR: [-0.12, 0.38, 0.26],
          handL: [0.15, 0.52, -0.14], handR: [-0.15, 0.52, -0.14],
        },
      },
      {
        t: 3,
        p: {
          kneeL: [0.12, 0.42, -0.3], footL: [0.12, 0.34, 0.08], toeL: [0.12, 0.42, 0.2],
          kneeR: [-0.12, 0.42, -0.3], footR: [-0.12, 0.34, 0.08], toeR: [-0.12, 0.42, 0.2],
          handL: [0.15, 0.49, -0.24], handR: [-0.15, 0.49, -0.24],
        },
      },
    ],
  },
  {
    id: 'figure-four',
    name: 'Liegende Taube',
    regions: ['hiprot'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 40,
    why: 'Dieselbe Dehnung wie die Taube – im Liegen, ohne Druck auf Knie und Hüfte. Perfekt abends.',
    feel: 'Gesäß des übergeschlagenen Beins',
    cues: [
      'Auf dem Rücken den Knöchel auf das andere Knie legen.',
      'Hinter den Oberschenkel greifen und ihn Richtung Brust ziehen.',
      'Das obere Knie sanft nach außen öffnen.',
    ],
    mistakes: ['Kopf und Schultern heben vom Boden ab.'],
    easier: 'Den unteren Fuß am Boden stehen lassen.',
    harder: 'Das untere Bein näher zur Brust ziehen.',
    pnf: 'Oberes Knie sanft gegen die Hand nach innen drücken.',
    cam: { az: 30, el: 44 },
    highlight: ['thighL'],
    ...HOLD,
    base: {
      ...SUPINE,
      kneeL: [0.42, 0.34, -0.05], toeL: [-0.12, 0.54, 0.02],
      elbowL: [0.3, 0.3, -0.3], elbowR: [-0.35, 0.3, -0.3],
    },
    frames: [
      {
        t: 0,
        p: {
          kneeR: [-0.1, 0.5, -0.04], footR: [-0.1, 0.44, 0.36], toeR: [-0.1, 0.5, 0.5],
          footL: [-0.04, 0.53, 0.0], handL: [-0.02, 0.4, -0.14], handR: [-0.17, 0.4, -0.14],
        },
      },
      {
        t: 3,
        p: {
          kneeR: [-0.1, 0.46, -0.16], footR: [-0.1, 0.5, 0.26], toeR: [-0.1, 0.58, 0.38],
          footL: [-0.04, 0.53, -0.1], handL: [-0.02, 0.38, -0.22], handR: [-0.17, 0.38, -0.22],
        },
      },
    ],
  },
  // ---------- Hüfte & Beine ----------
  {
    id: 'couch-stretch',
    name: 'Couch-Stretch',
    regions: ['hipflex'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 40,
    why: 'Die intensivste Dehnung für Hüftbeuger und vorderen Oberschenkel zugleich – die Stufe nach dem normalen Hüftbeuger-Dehnen.',
    feel: 'Vorn am Oberschenkel bis in die Hüfte',
    cues: [
      'Hinteres Knie an die Wand, der Fuß steht senkrecht an der Wand.',
      'Vorderen Fuß aufstellen, Oberkörper langsam aufrichten.',
      'Gesäß anspannen und das Becken leicht nach vorn schieben.',
    ],
    mistakes: ['Hohlkreuz – Rippen runter, Gesäß fest.'],
    easier: 'Oberkörper nach vorn lehnen, Hände auf dem vorderen Knie.',
    harder: 'Ganz aufrecht, die Arme über den Kopf.',
    pnf: 'Hinteren Fuß sanft gegen die Wand drücken.',
    cam: { az: 68, el: 12 },
    highlight: ['thighL'],
    props: [{ type: 'wall', z: -0.46 }],
    ...HOLD,
    base: {
      pUp: [0, 1, -0.05], cUp: [0, 1, 0.02],
      kneeL: [0.1, -0.1, -0.32], footL: [0.1, 0.46, -0.4], toeL: [0.1, 0.62, -0.42],
      footR: [-0.12, 0.08, 0.5], kneeR: [-0.12, 0.6, 0.6], toeR: [-0.13, 0.03, 0.67],
      handL: [0.05, 0.62, 0.42], handR: [-0.15, 0.62, 0.42],
      elbowL: [0.35, 0.8, 0.1], elbowR: [-0.4, 0.8, 0.1],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.53, -0.1] } },
      { t: 3, p: { pelvis: [0, 0.5, -0.02] } },
    ],
  },
  {
    id: 'lizard',
    name: 'Eidechse',
    regions: ['hipflex', 'hiprot', 'adductors'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 45,
    why: 'Tiefer Ausfallschritt, der Hüftbeuger, Leiste und Hüftrotation zusammen öffnet – eine der besten Übungen für Kicks und Spagat.',
    feel: 'Leiste vorn und Hüftbeuger hinten',
    cues: [
      'Tiefer Ausfallschritt, beide Hände innen neben den vorderen Fuß.',
      'Hinteres Knie ablegen, die Hüfte sinkt nach vorn-unten.',
      'Wenn es geht, die Ellbogen Richtung Boden senken.',
    ],
    mistakes: ['Das vordere Knie kippt nach innen – es zeigt über den Fuß.'],
    easier: 'Auf den Händen bleiben, Hüfte höher.',
    harder: 'Unterarme ablegen oder das vordere Knie sanft nach außen öffnen.',
    pnf: 'Vorderen Fuß sanft in den Boden drücken, als wolltest du ihn zu dir ziehen.',
    cam: { az: 60, el: 20 },
    highlight: ['thighL', 'thighR'],
    ...HOLD,
    base: {
      pUp: [0, 0.6, 1], pFwd: [0, -1, 0.6], cFwd: [0, -1, 0.3],
      footL: [0.3, 0.08, 0.55], toeL: [0.33, 0.03, 0.72], kneeL: [0.5, 0.55, 0.6],
      kneeR: [-0.12, -0.1, -0.36], footR: [-0.12, 0.07, -0.76], toeR: [-0.12, 0.02, -0.92],
      handL: [0.12, 0.06, 0.56], handR: [-0.1, 0.06, 0.56],
      elbowL: [0.2, 0.3, 0.6], elbowR: [-0.3, 0.3, 0.5],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.38, 0.0], cUp: [0, 0.3, 1] } },
      { t: 3, p: { pelvis: [0.02, 0.33, 0.07], cUp: [0, 0.15, 1] } },
    ],
  },
  {
    id: 'half-split',
    name: 'Halber Spagat',
    regions: ['hamstrings'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 40,
    why: 'Die direkteste Dehnung für den Beinbeuger – und der erste Schritt zum Frontspagat.',
    feel: 'Rückseite des vorderen Beins',
    cues: [
      'Hinteres Knie unter der Hüfte, vorderes Bein gestreckt, Zehen zeigen nach oben.',
      'Hüfte nach hinten schieben, Rücken lang.',
      'Aus der Hüfte nach vorn kippen, Hände neben dem Bein.',
    ],
    mistakes: ['Den Rücken rund machen statt aus der Hüfte zu kippen.'],
    easier: 'Hände auf Bücher oder Blöcke stellen, das vordere Knie leicht beugen.',
    harder: 'Brust Richtung Knie senken.',
    pnf: 'Vordere Ferse sanft in den Boden drücken.',
    cam: { az: 70, el: 14 },
    highlight: ['thighL'],
    ...HOLD,
    base: {
      pelvis: [0, 0.5, -0.12],
      kneeR: [-0.1, -0.2, -0.12], footR: [-0.1, 0.07, -0.55], toeR: [-0.1, 0.02, -0.7],
      footL: [0.1, 0.08, 0.72], kneeL: [0.1, 0.6, 0.35], toeL: [0.1, 0.25, 0.76],
      elbowL: [0.35, 0.35, 0.2], elbowR: [-0.35, 0.35, 0.2],
    },
    frames: [
      { t: 0, p: { pUp: [0, 0.7, 1], cUp: [0, 0.45, 1], handL: [0.25, 0.1, 0.3], handR: [-0.08, 0.1, 0.3] } },
      { t: 3, p: { pUp: [0, 0.45, 1], cUp: [0, 0.08, 1], handL: [0.25, 0.06, 0.42], handR: [-0.08, 0.06, 0.42] } },
    ],
  },
  {
    id: 'seated-pike',
    name: 'Sitzende Vorbeuge',
    regions: ['hamstrings', 'lowback'],
    kind: 'stretch',
    type: 'hold',
    sides: false,
    seconds: 45,
    why: 'Dehnt beide Beinrückseiten zusammen – mit langem Rücken der Weg, irgendwann flach über den Beinen zu liegen.',
    feel: 'Rückseite beider Beine',
    cues: [
      'Beine lang nach vorn, Zehen zeigen nach oben.',
      'Becken nach vorn kippen, Brust lang nach vorn schieben.',
      'Mit jedem Ausatmen ein kleines Stück tiefer.',
    ],
    mistakes: ['Rundrücken und am Fuß ziehen.'],
    easier: 'Auf ein Kissen setzen, die Knie leicht beugen.',
    harder: 'Handtuch um die Füße und sanft ziehen.',
    pnf: 'Fersen sanft in den Boden drücken.',
    cam: { az: 90, el: 16 },
    highlight: ['thighL', 'thighR'],
    ...HOLD,
    base: {
      pelvis: [0, 0.14, 0],
      footL: [0.1, 0.07, 0.86], footR: [-0.1, 0.07, 0.86], toeL: [0.1, 0.22, 0.9], toeR: [-0.1, 0.22, 0.9],
      kneeL: [0.1, 0.6, 0.45], kneeR: [-0.1, 0.6, 0.45],
      elbowL: [0.3, 0.3, 0.4], elbowR: [-0.3, 0.3, 0.4],
    },
    frames: [
      { t: 0, p: { pUp: [0, 1, 0.3], cUp: [0, 1, 0.8], handL: [0.14, 0.12, 0.55], handR: [-0.14, 0.12, 0.55] } },
      { t: 3, p: { pUp: [0, 1, 0.6], cUp: [0, 1, 1.6], handL: [0.12, 0.1, 0.72], handR: [-0.12, 0.1, 0.72] } },
    ],
  },
  {
    id: 'adductor-rockback',
    name: 'Adduktoren-Rock-Back',
    regions: ['adductors'],
    kind: 'dynamic',
    type: 'flow',
    sides: true,
    seconds: 40,
    tempo: 'Langsam, ca. 8 pro Seite',
    why: 'Dehnt die Innenseite des gestreckten Beins in Bewegung – ein sicherer Weg zu breiteren Ständen und Seitspagat.',
    feel: 'Innenseite des ausgestreckten Beins',
    cues: [
      'Vierfüßlerstand, ein Bein gestreckt zur Seite, der Fuß steht flach.',
      'Gesäß langsam Richtung Ferse des Knie-Beins schieben.',
      'Rücken lang lassen, dann wieder nach vorn.',
    ],
    mistakes: ['Rundrücken beim Zurückschieben.'],
    easier: 'Das gestreckte Bein etwas beugen.',
    harder: 'Hinten zwei Atemzüge halten.',
    cam: { az: 20, el: 30 },
    highlight: ['thighL'],
    loop: 5,
    base: {
      ...QUAD,
      footL: [0.85, 0.07, -0.05], toeL: [0.88, 0.02, 0.12], kneeL: [0.5, 0.45, -0.1],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.55, -0.06] } },
      { t: 1, p: { pelvis: [0, 0.55, -0.06] } },
      { t: 2.5, p: { pelvis: [-0.05, 0.43, -0.34], pUp: [0, 0.3, 1] } },
      { t: 3.5, p: { pelvis: [-0.05, 0.43, -0.34], pUp: [0, 0.3, 1] } },
    ],
  },
  {
    id: 'hip-cars',
    name: 'Hüftkreisen im Stand',
    regions: ['hiprot'],
    kind: 'dynamic',
    type: 'flow',
    sides: true,
    seconds: 30,
    tempo: 'Langsam, ca. 5 große Kreise pro Seite',
    why: 'Kontrollierte Kreise durch den ganzen Bewegungsweg der Hüfte – das Aufwärmen vor Tritten schlechthin.',
    feel: 'Rund um das Hüftgelenk des Kreisbeins',
    cues: [
      'Seitlich an der Wand festhalten, aufrecht stehen.',
      'Knie hoch vor den Körper, dann weit zur Seite öffnen.',
      'Nach hinten führen und langsam absetzen – das Becken bleibt ruhig.',
    ],
    mistakes: ['Mit dem Oberkörper mitkippen.'],
    easier: 'Kleinere Kreise.',
    harder: 'Ohne Festhalten.',
    cam: { az: 30, el: 10 },
    highlight: ['thighL'],
    props: [{ type: 'wall', x: -0.56 }],
    mat: { hidden: true },
    smooth: true,
    loop: 6,
    base: { ...STAND, ...WALL_RIGHT, handL: [0.26, 0.98, 0.06], elbowL: [0.45, 1.1, -0.1] },
    frames: [
      { t: 0, p: { kneeL: [0.12, 0.95, 0.44], footL: [0.12, 0.55, 0.36], toeL: [0.12, 0.5, 0.52] } },
      { t: 1.5, p: { kneeL: [0.5, 0.92, 0.18], footL: [0.52, 0.52, 0.12], toeL: [0.56, 0.48, 0.28] } },
      { t: 3, p: { kneeL: [0.42, 0.78, -0.24], footL: [0.56, 0.88, -0.56], toeL: [0.62, 0.95, -0.7] } },
      { t: 4.5, p: { kneeL: [0.12, 0.55, -0.08], footL: [0.12, 0.28, -0.42], toeL: [0.12, 0.3, -0.58] } },
    ],
  },
  {
    id: 'leg-swing-side',
    name: 'Beinpendel seitlich',
    regions: ['adductors', 'hiprot'],
    kind: 'dynamic',
    type: 'flow',
    sides: true,
    seconds: 30,
    tempo: 'Locker, ca. 15 pro Seite',
    why: 'Öffnet die Hüfte zur Seite – bereitet Round- und Seitkicks vor.',
    feel: 'Innenseite und Außenseite der Hüfte',
    cues: [
      'Mit beiden Händen an der Wand abstützen.',
      'Ein Bein locker vor dem Körper von Seite zu Seite schwingen.',
      'Den Schwung langsam größer werden lassen.',
    ],
    mistakes: ['Das Standbein knickt ein – leicht gebeugt, aber stabil.'],
    easier: 'Kleiner schwingen.',
    harder: 'Höher schwingen, Oberkörper bleibt ruhig.',
    cam: { az: 180, el: 12 },
    highlight: ['thighL'],
    props: [{ type: 'wall', z: 0.55 }],
    mat: { hidden: true },
    loop: 1.8,
    base: {
      ...STAND,
      pelvis: [0, 0.97, 0.02],
      handL: [0.24, 1.25, 0.52], handR: [-0.24, 1.25, 0.52],
      elbowL: [0.45, 1.05, 0.3], elbowR: [-0.45, 1.05, 0.3],
      cUp: [0, 1, 0.12],
    },
    frames: [
      { t: 0, p: { footL: [0.62, 0.36, 0.08], kneeL: [0.4, 0.7, 0.3], toeL: [0.66, 0.34, 0.25] } },
      { t: 0.9, p: { footL: [-0.38, 0.26, 0.14], kneeL: [-0.15, 0.6, 0.35], toeL: [-0.42, 0.24, 0.3] } },
    ],
  },
  {
    id: 'ninety-liftoff',
    name: '90/90 mit Anheben',
    regions: ['hiprot'],
    kind: 'active',
    type: 'flow',
    sides: true,
    seconds: 30,
    tempo: 'Ca. 6 pro Seite, oben kurz halten',
    reps: 6,
    why: 'Hebt das hintere Bein aus der 90/90-Position – Kraft genau dort, wo die Hüfte sonst nachgibt. Wichtig für Kicks.',
    feel: 'Seitlich und hinten in der Hüfte des hinteren Beins',
    cues: [
      'Im 90/90-Sitz aufrecht bleiben, Hände hinten abstützen.',
      'Den hinteren Fuß und das Knie wenige Zentimeter vom Boden heben.',
      'Oben kurz halten und langsam absenken.',
    ],
    mistakes: ['Mit dem Oberkörper wegkippen, um das Bein hochzubekommen.'],
    easier: 'Nur den Fuß heben, das Knie bleibt am Boden.',
    harder: 'Ohne Hände abstützen.',
    cam: { az: -130, el: 26 },
    highlight: ['thighR'],
    loop: 4.8,
    base: {
      pelvis: [0, 0.15, 0], pUp: [0, 1, -0.05], cUp: [0, 1, -0.05],
      footL: [-0.32, 0.07, 0.46], kneeL: [0.09, 0.02, 0.48], toeL: [-0.48, 0.05, 0.44],
      handL: [0.22, 0.06, -0.32], handR: [-0.22, 0.06, -0.32],
      elbowL: [0.4, 0.3, -0.3], elbowR: [-0.4, 0.3, -0.3],
    },
    frames: [
      { t: 0, p: { footR: [-0.56, 0.07, -0.42], kneeR: [-0.58, 0.02, 0.0], toeR: [-0.57, 0.05, -0.58] } },
      { t: 0.8, p: { footR: [-0.56, 0.07, -0.42], kneeR: [-0.58, 0.02, 0.0], toeR: [-0.57, 0.05, -0.58] } },
      { t: 1.8, p: { footR: [-0.52, 0.3, -0.4], kneeR: [-0.56, 0.22, 0.0], toeR: [-0.53, 0.3, -0.56] } },
      { t: 3.4, p: { footR: [-0.52, 0.3, -0.4], kneeR: [-0.56, 0.22, 0.0], toeR: [-0.53, 0.3, -0.56] } },
    ],
  },
  {
    id: 'pancake-reach',
    name: 'Pancake aktiv',
    regions: ['adductors', 'hamstrings'],
    kind: 'active',
    type: 'flow',
    sides: false,
    seconds: 45,
    tempo: 'Langsam, ca. 6 Wiederholungen',
    reps: 6,
    why: 'Aus der Grätsche aktiv nach vorn kippen und wieder aufrichten – kräftigt die Hüfte in der Dehnung. Der Weg zu tiefer Grätsche und hohen Kicks.',
    feel: 'Innenseite der Beine und Hüftbeuger vorn',
    cues: [
      'Breite Grätsche, Zehen nach oben, Rücken lang.',
      'Aus der Hüfte nach vorn kippen, die Hände gleiten am Boden nach vorn.',
      'Mit geradem Rücken wieder aufrichten.',
    ],
    mistakes: ['Nur den Rücken rund machen – die Bewegung kommt aus der Hüfte.'],
    easier: 'Kissen unter das Gesäß.',
    harder: 'Arme vor der Brust verschränken.',
    cam: { az: 20, el: 30 },
    highlight: ['thighL', 'thighR'],
    loop: 4.8,
    base: {
      pelvis: [0, 0.15, 0],
      footL: [0.64, 0.07, 0.55], footR: [-0.64, 0.07, 0.55],
      kneeL: [0.4, 0.45, 0.35], kneeR: [-0.4, 0.45, 0.35],
      toeL: [0.66, 0.22, 0.6], toeR: [-0.66, 0.22, 0.6],
      elbowL: [0.4, 0.35, 0.3], elbowR: [-0.4, 0.35, 0.3],
    },
    frames: [
      { t: 0, p: { pUp: [0, 1, 0.08], cUp: [0, 1, 0.1], handL: [0.3, 0.1, 0.3], handR: [-0.3, 0.1, 0.3] } },
      { t: 0.6, p: { pUp: [0, 1, 0.08], cUp: [0, 1, 0.1], handL: [0.3, 0.1, 0.3], handR: [-0.3, 0.1, 0.3] } },
      { t: 2.2, p: { pUp: [0, 1, 0.6], cUp: [0, 1, 1.2], handL: [0.22, 0.07, 0.7], handR: [-0.22, 0.07, 0.7] } },
      { t: 3.2, p: { pUp: [0, 1, 0.6], cUp: [0, 1, 1.2], handL: [0.22, 0.07, 0.7], handR: [-0.22, 0.07, 0.7] } },
    ],
  },
  {
    id: 'leg-raise-front',
    name: 'Beinheben vorn',
    regions: ['hamstrings', 'hipflex'],
    kind: 'active',
    type: 'flow',
    sides: true,
    seconds: 40,
    tempo: 'Ca. 6 pro Seite, oben 2 Sekunden halten',
    reps: 6,
    why: 'Aktive Beweglichkeit: das gestreckte Bein aus eigener Kraft heben. Genau das braucht ein hoher Frontkick – Dehnen allein reicht dafür nicht.',
    feel: 'Vorn an der Hüfte (arbeitet) und hinten am Oberschenkel (dehnt)',
    cues: [
      'Seitlich an der Wand festhalten, aufrecht stehen.',
      'Das gestreckte Bein ohne Schwung so hoch wie möglich heben.',
      'Oben zwei Sekunden halten, langsam absenken.',
    ],
    mistakes: ['Schwung holen oder mit dem Oberkörper nach hinten lehnen.'],
    easier: 'Das Knie leicht gebeugt lassen.',
    harder: 'Oben 5 Sekunden halten.',
    cam: { az: 70, el: 8 },
    highlight: ['thighL'],
    props: [{ type: 'wall', x: -0.56 }],
    mat: { hidden: true },
    loop: 6,
    base: { ...STAND, ...WALL_RIGHT, handL: [0.26, 0.98, 0.06], elbowL: [0.45, 1.1, -0.1] },
    frames: [
      { t: 0, p: { footL: [0.11, 0.08, 0], kneeL: [0.11, 0.5, 0.3], toeL: [0.13, 0.03, 0.17] } },
      { t: 0.6, p: { footL: [0.11, 0.08, 0.02], kneeL: [0.11, 0.5, 0.3], toeL: [0.13, 0.03, 0.19] } },
      { t: 2.2, p: { footL: [0.1, 0.84, 0.82], kneeL: [0.1, 1.3, 0.45], toeL: [0.1, 0.98, 0.9] } },
      { t: 4.2, p: { footL: [0.1, 0.84, 0.82], kneeL: [0.1, 1.3, 0.45], toeL: [0.1, 0.98, 0.9] } },
    ],
  },
  {
    id: 'leg-raise-side',
    name: 'Beinheben seitlich',
    regions: ['adductors', 'hiprot'],
    kind: 'active',
    type: 'flow',
    sides: true,
    seconds: 40,
    tempo: 'Ca. 6 pro Seite, oben 2 Sekunden halten',
    reps: 6,
    why: 'Kräftigt die seitliche Hüfte in großer Öffnung – die Basis für Seit- und Roundkicks mit Kontrolle.',
    feel: 'Außen an der Hüfte (arbeitet) und innen am Oberschenkel (dehnt)',
    cues: [
      'Seitlich an der Wand festhalten, Oberkörper aufrecht.',
      'Das gestreckte Bein zur Seite heben, Zehen zeigen nach vorn.',
      'Oben halten, ohne den Oberkörper wegzukippen.',
    ],
    mistakes: ['Das Bein nach vorn drehen oder die Hüfte hochziehen.'],
    easier: 'Weniger hoch, dafür sauber.',
    harder: 'Oben 5 Sekunden halten.',
    cam: { az: 20, el: 8 },
    highlight: ['thighL'],
    props: [{ type: 'wall', x: -0.56 }],
    mat: { hidden: true },
    loop: 6,
    base: { ...STAND, ...WALL_RIGHT, handL: [0.26, 0.98, 0.06], elbowL: [0.45, 1.1, -0.1] },
    frames: [
      { t: 0, p: { footL: [0.11, 0.08, 0], kneeL: [0.11, 0.5, 0.3], toeL: [0.13, 0.03, 0.17], cUp: [0, 1, 0] } },
      { t: 0.6, p: { footL: [0.12, 0.08, 0], kneeL: [0.12, 0.5, 0.3], toeL: [0.14, 0.03, 0.17], cUp: [0, 1, 0] } },
      { t: 2.2, p: { footL: [0.7, 0.4, 0.04], kneeL: [0.45, 0.8, 0.3], toeL: [0.74, 0.36, 0.2], cUp: [-0.12, 1, 0] } },
      { t: 4.2, p: { footL: [0.7, 0.4, 0.04], kneeL: [0.45, 0.8, 0.3], toeL: [0.74, 0.36, 0.2], cUp: [-0.12, 1, 0] } },
    ],
  },
  {
    id: 'soleus-wall',
    name: 'Tiefe Wade an der Wand',
    regions: ['calves'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 30,
    why: 'Mit gebeugtem Knie dehnt sich der tiefe Wadenmuskel (Soleus) – der begrenzt die Kniebeuge und wird beim Laufen hart.',
    feel: 'Tief unten in der Wade, nahe der Achillessehne',
    cues: [
      'Hände an die Wand, kleiner Schritt nach hinten.',
      'Beide Knie beugen, die hintere Ferse bleibt am Boden.',
      'Gewicht langsam nach vorn-unten verlagern.',
    ],
    mistakes: ['Die Ferse hebt ab.'],
    easier: 'Kleinerer Schritt.',
    harder: 'Tiefer in die Knie gehen.',
    pnf: 'Hinteren Fußballen sanft in den Boden drücken.',
    cam: { az: 104, el: 10 },
    highlight: ['shinL'],
    props: [{ type: 'wall', z: 0.62 }],
    mat: { z: 0.0 },
    ...HOLD,
    base: {
      pUp: [0, 1, 0.25], pFwd: [0, -0.25, 1], cUp: [0, 1, 0.3],
      footL: [0.12, 0.08, -0.28], toeL: [0.13, 0.03, -0.11], kneeL: [0.12, 0.45, 0.4],
      footR: [-0.12, 0.08, 0.3], toeR: [-0.13, 0.03, 0.47], kneeR: [-0.12, 0.55, 0.7],
      handL: [0.22, 1.12, 0.6], handR: [-0.22, 1.12, 0.6],
      elbowL: [0.45, 0.95, 0.35], elbowR: [-0.45, 0.95, 0.35],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.78, 0.04] } },
      { t: 3, p: { pelvis: [0, 0.72, 0.1] } },
    ],
  },
  {
    id: 'shin-stretch',
    name: 'Fersensitz',
    regions: ['calves'],
    kind: 'stretch',
    type: 'hold',
    sides: false,
    seconds: 40,
    why: 'Dehnt Schienbein und Fußrücken – beim Laufen und Kicken ständig unter Spannung, beim Dehnen fast immer vergessen.',
    feel: 'Vorn am Schienbein und auf dem Fußrücken',
    cues: [
      'Knien, Fußrücken flach am Boden, auf die Fersen setzen.',
      'Aufrecht sitzen, Hände auf die Oberschenkel.',
      'Wer mehr will: Hände hinter die Füße, leicht zurücklehnen.',
    ],
    mistakes: ['Die Fersen fallen nach außen.'],
    easier: 'Ein gefaltetes Handtuch unter die Fußgelenke.',
    harder: 'Zurücklehnen und die Knie leicht anheben.',
    cam: { az: 90, el: 12 },
    highlight: ['shinL', 'shinR'],
    ...HOLD,
    base: {
      footL: [0.1, 0.07, -0.32], toeL: [0.1, 0.02, -0.48], kneeL: [0.13, -0.2, 0.25],
      footR: [-0.1, 0.07, -0.32], toeR: [-0.1, 0.02, -0.48], kneeR: [-0.13, -0.2, 0.25],
      elbowL: [0.3, 0.5, -0.2], elbowR: [-0.3, 0.5, -0.2],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.32, -0.26], pUp: [0, 1, -0.05], cUp: [0, 1, -0.05], handL: [0.14, 0.34, 0.02], handR: [-0.14, 0.34, 0.02] } },
      { t: 3, p: { pelvis: [0, 0.33, -0.28], pUp: [0, 1, -0.3], cUp: [0, 1, -0.3], handL: [0.17, 0.1, -0.36], handR: [-0.17, 0.1, -0.36] } },
    ],
  },
  {
    id: 'quad-standing',
    name: 'Oberschenkel vorn im Stand',
    regions: ['hipflex'],
    kind: 'stretch',
    type: 'hold',
    sides: true,
    seconds: 30,
    why: 'Geht überall, auch nach dem Laufen: dehnt den vorderen Oberschenkel und mit dem Becken nach vorn auch den Hüftbeuger.',
    feel: 'Vorn am Oberschenkel',
    cues: [
      'An der Wand festhalten, die Ferse zum Gesäß ziehen.',
      'Knie zeigt nach unten, die Knie bleiben nebeneinander.',
      'Gesäß anspannen und das Becken leicht nach vorn schieben.',
    ],
    mistakes: ['Das Knie wandert nach vorn oder zur Seite.'],
    easier: 'Mit einem Handtuch um den Fuß greifen.',
    harder: 'Knie etwas nach hinten führen.',
    pnf: 'Fuß sanft gegen die Hand drücken.',
    cam: { az: 55, el: 8 },
    highlight: ['thighL'],
    props: [{ type: 'wall', x: -0.56 }],
    mat: { hidden: true },
    ...HOLD,
    base: {
      ...STAND, ...WALL_RIGHT,
      footL: [0.1, 0.9, -0.16], toeL: [0.1, 1.04, -0.2],
      handL: [0.12, 0.92, -0.2], elbowL: [0.4, 1.1, -0.2],
    },
    frames: [
      { t: 0, p: { pelvis: [0, 0.98, 0], kneeL: [0.1, 0.4, 0.1] } },
      { t: 3, p: { pelvis: [0, 0.98, 0.03], kneeL: [0.1, 0.42, -0.08] } },
    ],
  },
  {
    id: 'squat-shift',
    name: 'Hocke mit Gewichtsverlagerung',
    regions: ['calves', 'adductors'],
    kind: 'dynamic',
    type: 'flow',
    sides: false,
    seconds: 45,
    tempo: 'Langsam von Seite zu Seite',
    why: 'Bewegung in der tiefen Hocke: Sprunggelenke und Hüften arbeiten abwechselnd tiefer – die Stufe nach dem ruhigen Hocken.',
    feel: 'Wade und Leiste der Seite, auf die du dich verlagerst',
    cues: [
      'Tiefe Hocke, Fersen am Boden.',
      'Gewicht langsam über ein Knie schieben, das Knie wandert über die Zehen.',
      'Durch die Mitte zur anderen Seite.',
    ],
    mistakes: ['Fersen heben ab.'],
    easier: 'Vorn an einem Türrahmen festhalten.',
    harder: 'Auf jeder Seite drei Atemzüge bleiben.',
    cam: { az: 25, el: 14 },
    highlight: ['shinL', 'shinR'],
    smooth: true,
    loop: 5,
    base: {
      footL: [0.2, 0.08, 0], footR: [-0.2, 0.08, 0],
      toeL: [0.27, 0.03, 0.16], toeR: [-0.27, 0.03, 0.16],
      pUp: [0, 1, 0.1], pFwd: [0, -0.1, 1], cUp: [0, 1, 0.45],
      kneeL: [0.38, 0.5, 0.36], kneeR: [-0.38, 0.5, 0.36],
      elbowL: [0.3, 0.55, 0.32], elbowR: [-0.3, 0.55, 0.32],
    },
    frames: [
      { t: 0, p: { pelvis: [0.1, 0.34, -0.06], handL: [0.12, 0.72, 0.33], handR: [0.08, 0.72, 0.33] } },
      { t: 2.5, p: { pelvis: [-0.1, 0.34, -0.06], handL: [-0.08, 0.72, 0.33], handR: [-0.12, 0.72, 0.33] } },
    ],
  },
];

// Alles zusammen, mit Einordnung
export const EXERCISES = [
  ...BASE_EXERCISES.map((ex) => ({ ...ex, ...(META[ex.id] || {}) })),
  ...EXTRA,
];
const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));
// Stufen in beide Richtungen verknüpfen: up = nächste Stufe, down = leichtere
EXERCISES.forEach((e) => {
  const next = e.up && BY_ID.get(e.up);
  if (next && !next.down) next.down = e.id;
});
export function exercise(id) { return BY_ID.get(id) || null; }

export function exercisesOfRegion(region) {
  return EXERCISES.filter((e) => e.regions.includes(region));
}

// Übungen, die sich gegenseitig ersetzen können (gleiche Hauptregion, gleiche Art)
export function alternativesFor(id, exclude = []) {
  const ex = exercise(id);
  if (!ex) return [];
  const main = ex.regions[0];
  return EXERCISES.filter((e) => e.id !== id && !exclude.includes(e.id) && e.regions[0] === main && e.kind === ex.kind);
}
